import Database from 'better-sqlite3';
import { createHash, randomUUID } from 'node:crypto';
import { mkdirSync, readFileSync, readdirSync } from 'node:fs';
import { createServer } from 'node:http';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const dataDirectory = join(root, 'data');
mkdirSync(dataDirectory, { recursive: true });
const databasePath = process.env.DATABASE_PATH ?? join(dataDirectory, 'database.sqlite');
const db = new Database(databasePath);
db.pragma('journal_mode = WAL');
db.pragma('foreign_keys = ON');

const migrationDirectory = join(root, 'server', 'migrations');
db.exec('CREATE TABLE IF NOT EXISTS schema_migrations (version INTEGER PRIMARY KEY, applied_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)');
for (const file of readdirSync(migrationDirectory).filter((name) => name.endsWith('.sql')).sort()) {
  const version = Number(file.split('_')[0]);
  if (!db.prepare('SELECT 1 FROM schema_migrations WHERE version = ?').get(version)) {
    db.transaction(() => { db.exec(readFileSync(join(migrationDirectory, file), 'utf8')); db.prepare('INSERT INTO schema_migrations (version) VALUES (?)').run(version); })();
  }
}

const passwordHash = (value) => createHash('sha256').update(value).digest('hex');
const now = new Date().toISOString();
if (db.prepare('SELECT count(*) AS count FROM users').get().count === 0) {
  const insertUser = db.prepare('INSERT INTO users (id, first_name, last_name, email, password_hash, role, favorite_sport, avatar_url, profile_color, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)');
  insertUser.run('user-admin', 'Local', 'Admin', 'admin@ligadokapsy.cz', passwordHash('password'), 'admin', 'football', null, '#10B981', now);
  insertUser.run('user-demo', 'Demo', 'User', 'user@ligadokapsy.cz', passwordHash('password'), 'user', 'hockey', null, '#38BDF8', now);
}
if (db.prepare('SELECT count(*) AS count FROM teams').get().count === 0) {
  const insert = db.prepare('INSERT INTO teams (id, name, primary_sport, color, logo_url, created_by) VALUES (?, ?, ?, ?, ?, ?)');
  insert.run('team-lions', 'Prague Lions', 'football', '#10B981', null, 'user-admin'); insert.run('team-wolves', 'Brno Wolves', 'football', '#38BDF8', null, 'user-demo'); insert.run('team-bears', 'Ostrava Bears', 'basketball', '#F59E0B', null, 'user-admin'); insert.run('team-eagles', 'Plzeň Eagles', 'tennis', '#A78BFA', null, 'user-demo');
}
if (db.prepare('SELECT count(*) AS count FROM tournaments').get().count === 0) {
  const insert = db.prepare('INSERT INTO tournaments (id, name, sport, location, start_date, status, logo_url, created_by) VALUES (?, ?, ?, ?, ?, ?, ?, ?)');
  insert.run('tournament-spring', 'Spring Football Cup', 'football', 'Prague', '2026-05-10', 'published', null, 'user-admin'); insert.run('tournament-city', 'City Basketball Open', 'basketball', 'Brno', '2026-06-21', 'draft', null, 'user-demo');
  db.prepare('INSERT INTO tournament_teams (id, tournament_id, team_id) VALUES (?, ?, ?)').run('tt-spring-lions', 'tournament-spring', 'team-lions'); db.prepare('INSERT INTO tournament_teams (id, tournament_id, team_id) VALUES (?, ?, ?)').run('tt-spring-wolves', 'tournament-spring', 'team-wolves'); db.prepare('INSERT INTO tournament_teams (id, tournament_id, team_id) VALUES (?, ?, ?)').run('tt-city-bears', 'tournament-city', 'team-bears');
}
if (db.prepare('SELECT count(*) AS count FROM matches').get().count === 0) {
  db.prepare('INSERT INTO matches (id, tournament_id, home_team_id, away_team_id, match_date, match_time, pitch_location, status) VALUES (?, ?, ?, ?, ?, ?, ?, ?)').run('match-spring-1', 'tournament-spring', 'team-lions', 'team-wolves', '2026-05-10', '10:00', 'Main Pitch', 'scheduled');
}

function profile(row) { return row && { id: row.id, first_name: row.first_name, last_name: row.last_name, email: row.email, role: row.role, favoriteSport: row.favorite_sport, avatarUrl: row.avatar_url, profileColor: row.profile_color, createdAt: row.created_at, language: row.language }; }
function team(row) { return row && { id: row.id, name: row.name, primary_sport: row.primary_sport, color: row.color, logo_url: row.logo_url, created_by: row.created_by, is_private: Boolean(row.is_private) }; }
function tournament(row) { return row && { id: row.id, name: row.name, sport: row.sport, location: row.location, start_date: row.start_date, status: row.status, logo_url: row.logo_url, created_by: row.created_by, rosters_locked: Boolean(row.rosters_locked), is_private: Boolean(row.is_private) }; }
function tournamentTeam(row) { return row && { id: row.id, tournament_id: row.tournament_id, team_id: row.team_id, rosters_locked: Boolean(row.rosters_locked) }; }
function rosterPlayer(row) { return row && { id: row.id, tournament_team_id: row.tournament_team_id, team_id: row.team_id, user_id: row.user_id, first_name: row.first_name, last_name: row.last_name, jersey_number: row.jersey_number ?? null, position: row.position ?? null, is_captain: Boolean(row.is_captain), created_at: row.created_at }; }
function sport(row) { return row && { id: row.id, name: row.name, code: row.code, active: Boolean(row.active), scoring_type: row.scoring_type, periods_config: row.periods_config }; }
function match(row) { return row && { id: row.id, tournament_id: row.tournament_id, home_team_id: row.home_team_id, away_team_id: row.away_team_id, match_date: row.match_date, match_time: row.match_time, pitch_location: row.pitch_location, status: row.status, home_score: row.home_score, away_score: row.away_score, clock_seconds: row.clock_seconds, clock_started_at: row.clock_started_at }; }
function event(row) { return row && { id: row.id, match_id: row.match_id, event_type: row.event_type, team_id: row.team_id, roster_player_id: row.roster_player_id ?? null, player_name: row.player_name, score_delta_home: row.score_delta_home, score_delta_away: row.score_delta_away, clock_seconds: row.clock_seconds, created_at: row.created_at }; }
function parseRosterLine(line) {
  const trimmed = line.trim();
  if (!trimmed) return { first_name: '', last_name: '', jersey_number: null };
  const match = trimmed.match(/^(?:(\d+)\s+)?(.+)$/);
  const jersey_number = match?.[1] ? Number(match[1]) : null;
  const name = (match?.[2] ?? trimmed).trim();
  const lastSpace = name.lastIndexOf(' ');
  if (lastSpace > 0) return { first_name: name.slice(0, lastSpace).trim(), last_name: name.slice(lastSpace + 1).trim(), jersey_number };
  return { first_name: name, last_name: '', jersey_number };
}
function cookie(request, name) { return request.headers.cookie?.split(';').map((value) => value.trim().split('=')).find(([key]) => key === name)?.[1]; }
function actor(request) { const token = request.headers.authorization?.replace('Bearer ', '') ?? cookie(request, 'ligadokapsy_session'); if (!token) return null; return db.prepare('SELECT u.* FROM sessions s JOIN users u ON u.id = s.user_id WHERE s.token = ? AND s.expires_at > ?').get(token, new Date().toISOString()); }
function manageable(record, user) { return user && (user.role === 'admin' || record.created_by === user.id); }
function canAccessTeam(teamId, user) {
  if (!user) return false;
  if (user.role === 'admin' || user.id === db.prepare('SELECT created_by FROM teams WHERE id = ?').get(teamId)?.created_by) return true;
  return db.prepare("SELECT 1 FROM entity_shares WHERE entity_type = 'team' AND entity_id = ? AND user_id = ?").get(teamId, user.id) !== undefined;
}
function canAccessTournament(tournamentId, user) {
  if (!user) return false;
  if (user.role === 'admin' || user.id === db.prepare('SELECT created_by FROM tournaments WHERE id = ?').get(tournamentId)?.created_by) return true;
  return db.prepare("SELECT 1 FROM entity_shares WHERE entity_type = 'competition' AND entity_id = ? AND user_id = ?").get(tournamentId, user.id) !== undefined;
}
function send(response, status, body, origin) { response.writeHead(status, { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': origin ?? '*', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Headers': 'Content-Type, Authorization', 'Access-Control-Allow-Methods': 'GET, POST, PATCH, DELETE, OPTIONS' }); response.end(JSON.stringify(body)); }
async function body(request) { let value = ''; for await (const chunk of request) { value += chunk; if (value.length > 10_000_000) throw new Error('request.tooLarge'); } return value ? JSON.parse(value) : {}; }

const server = createServer(async (request, response) => {
  const origin = request.headers.origin;
  if (request.method === 'OPTIONS') return send(response, 204, {}, origin);
  const url = new URL(request.url, 'http://localhost'); const path = url.pathname;
  try {
    if (path === '/api/health') return send(response, 200, { ok: true, databasePath }, origin);
    if (path === '/api/settings/language' && request.method === 'GET') { const setting = db.prepare("SELECT value FROM app_settings WHERE key = 'language'").get(); return send(response, 200, { language: setting?.value ?? null }, origin); }
    if (path === '/api/settings/language' && request.method === 'PUT') { const input = await body(request); if (!['cs', 'en'].includes(input.language)) return send(response, 400, { error: 'request.invalidLanguage' }, origin); db.prepare("INSERT INTO app_settings (key, value, updated_at) VALUES ('language', ?, CURRENT_TIMESTAMP) ON CONFLICT(key) DO UPDATE SET value = excluded.value, updated_at = CURRENT_TIMESTAMP").run(input.language); return send(response, 200, { language: input.language }, origin); }
    if (path === '/api/auth/sign-in' && request.method === 'POST') { const input = await body(request); const user = db.prepare('SELECT * FROM users WHERE email = ? COLLATE NOCASE').get(input.email); if (!user || user.password_hash !== passwordHash(input.password)) return send(response, 401, { error: 'auth.invalidCredentials' }, origin); const token = randomUUID(); db.prepare('INSERT INTO sessions (token, user_id, expires_at) VALUES (?, ?, ?)').run(token, user.id, new Date(Date.now() + 30 * 86400000).toISOString()); response.setHeader('Set-Cookie', `ligadokapsy_session=${token}; HttpOnly; Path=/; SameSite=Lax; Max-Age=2592000`); return send(response, 200, { profile: profile(user), token }, origin); }
    if (path === '/api/auth/sign-up' && request.method === 'POST') { const input = await body(request); if (db.prepare('SELECT 1 FROM users WHERE email = ? COLLATE NOCASE').get(input.email)) return send(response, 409, { error: 'auth.emailExists' }, origin); const id = randomUUID(); db.prepare('INSERT INTO users (id, first_name, last_name, email, password_hash, role, favorite_sport, profile_color, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)').run(id, input.firstName ?? 'User', input.lastName ?? '', input.email.toLowerCase(), passwordHash(input.password), 'user', 'football', '#10B981', new Date().toISOString()); const token = randomUUID(); db.prepare('INSERT INTO sessions (token, user_id, expires_at) VALUES (?, ?, ?)').run(token, id, new Date(Date.now() + 30 * 86400000).toISOString()); response.setHeader('Set-Cookie', `ligadokapsy_session=${token}; HttpOnly; Path=/; SameSite=Lax; Max-Age=2592000`); return send(response, 201, { profile: profile(db.prepare('SELECT * FROM users WHERE id = ?').get(id)), token }, origin); }
    if (path === '/api/auth/me' && request.method === 'GET') { const user = actor(request); return send(response, user ? 200 : 401, user ? { profile: profile(user) } : { error: 'auth.required' }, origin); }
    if (path === '/api/auth/sign-out' && request.method === 'POST') { const token = request.headers.authorization?.replace('Bearer ', '') ?? cookie(request, 'ligadokapsy_session'); if (token) db.prepare('DELETE FROM sessions WHERE token = ?').run(token); response.setHeader('Set-Cookie', 'ligadokapsy_session=; HttpOnly; Path=/; Max-Age=0'); return send(response, 200, { ok: true }, origin); }
    if (path === '/api/users' && request.method === 'GET') { const user = actor(request); if (user?.role !== 'admin') return send(response, 403, { error: 'admin.accessDenied' }, origin); return send(response, 200, db.prepare('SELECT * FROM users ORDER BY created_at').all().map(profile), origin); }
    if (path === '/api/admin/metrics' && request.method === 'GET') { const user = actor(request); if (user?.role !== 'admin') return send(response, 403, { error: 'admin.accessDenied' }, origin); return send(response, 200, { users: db.prepare('SELECT count(*) AS value FROM users').get().value, tournaments: db.prepare('SELECT count(*) AS value FROM tournaments').get().value, activeTournaments: db.prepare("SELECT count(*) AS value FROM tournaments WHERE status = 'published'").get().value, teams: db.prepare('SELECT count(*) AS value FROM teams').get().value, matches: db.prepare('SELECT count(*) AS value FROM matches').get().value, databaseBytes: db.pragma('page_count', { simple: true }) * db.pragma('page_size', { simple: true }) }, origin); }
    const userMatch = path.match(/^\/api\/users\/([^/]+)$/); if (userMatch && request.method === 'PATCH') { const user = actor(request); const id = userMatch[1]; if (!user || (user.role !== 'admin' && user.id !== id)) return send(response, 403, { error: 'admin.accessDenied' }, origin); const input = await body(request); if (input.role && user.role !== 'admin') return send(response, 403, { error: 'admin.accessDenied' }, origin); if (input.role === 'user' && id === user.id && db.prepare("SELECT count(*) AS value FROM users WHERE role = 'admin'").get().value <= 1) return send(response, 400, { error: 'admin.lastAdmin' }, origin); const current = db.prepare('SELECT * FROM users WHERE id = ?').get(id); const avatar = Object.hasOwn(input, 'avatarUrl') ? input.avatarUrl : current.avatar_url; db.prepare('UPDATE users SET first_name = coalesce(?, first_name), last_name = coalesce(?, last_name), email = coalesce(?, email), favorite_sport = coalesce(?, favorite_sport), avatar_url = ?, profile_color = coalesce(?, profile_color), language = coalesce(?, language), role = coalesce(?, role) WHERE id = ?').run(input.firstName ?? null, input.lastName ?? null, input.email ?? null, input.favoriteSport ?? null, avatar, input.profileColor ?? null, input.language ?? null, input.role ?? null, id); return send(response, 200, profile(db.prepare('SELECT * FROM users WHERE id = ?').get(id)), origin); }
    if (userMatch && request.method === 'DELETE') { const user = actor(request); if (user?.role !== 'admin') return send(response, 403, { error: 'admin.accessDenied' }, origin); const id = userMatch[1]; if (id === user.id && db.prepare("SELECT count(*) AS value FROM users WHERE role = 'admin'").get().value <= 1) return send(response, 400, { error: 'admin.lastAdmin' }, origin); db.transaction(() => { db.prepare('DELETE FROM tournaments WHERE created_by = ?').run(id); db.prepare('DELETE FROM teams WHERE created_by = ?').run(id); db.prepare('DELETE FROM users WHERE id = ?').run(id); })(); return send(response, 200, { ok: true }, origin); }
    if (path === '/api/teams' && request.method === 'GET') { const user = actor(request); let rows; if (user?.role === 'admin') rows = db.prepare('SELECT * FROM teams ORDER BY name').all(); else if (user) rows = db.prepare("SELECT t.* FROM teams t WHERE t.is_private = 0 OR t.created_by = ? OR EXISTS (SELECT 1 FROM entity_shares s WHERE s.entity_type = 'team' AND s.entity_id = t.id AND s.user_id = ?) ORDER BY t.name").all(user.id, user.id); else rows = db.prepare('SELECT * FROM teams WHERE is_private = 0 ORDER BY name').all(); return send(response, 200, rows.map(team), origin); }
    if (path === '/api/teams' && request.method === 'POST') { const user = actor(request); if (!user) return send(response, 401, { error: 'auth.required' }, origin); const input = await body(request); const id = randomUUID(); db.prepare('INSERT INTO teams (id, name, primary_sport, color, logo_url, is_private, created_by) VALUES (?, ?, ?, ?, ?, ?, ?)').run(id, input.name, input.primary_sport, input.color, input.logo_url ?? null, input.is_private ? 1 : 0, user.id); return send(response, 201, team(db.prepare('SELECT * FROM teams WHERE id = ?').get(id)), origin); }
    const teamMatch = path.match(/^\/api\/teams\/([^/]+)$/); if (teamMatch) { const current = db.prepare('SELECT * FROM teams WHERE id = ?').get(teamMatch[1]); const user = actor(request); if (!current) return send(response, 404, { error: 'teams.notFound' }, origin); if (current.is_private && !canAccessTeam(current.id, user)) return send(response, 403, { error: 'access.denied' }, origin); if (request.method === 'GET') return send(response, 200, team(current), origin); if (!manageable(current, user)) return send(response, 403, { error: 'teams.notAllowed' }, origin); if (request.method === 'DELETE') { db.prepare('DELETE FROM teams WHERE id = ?').run(current.id); return send(response, 200, { ok: true }, origin); } if (request.method === 'PATCH') { const input = await body(request); db.prepare('UPDATE teams SET name = ?, primary_sport = ?, color = ?, logo_url = ?, is_private = ? WHERE id = ?').run(input.name, input.primary_sport, input.color, input.logo_url ?? null, input.is_private ? 1 : 0, current.id); return send(response, 200, team(db.prepare('SELECT * FROM teams WHERE id = ?').get(current.id)), origin); } }
    if (path === '/api/tournaments' && request.method === 'GET') { const user = actor(request); let rows; if (user?.role === 'admin') rows = db.prepare('SELECT * FROM tournaments ORDER BY start_date').all(); else if (user) rows = db.prepare("SELECT t.* FROM tournaments t WHERE t.is_private = 0 OR t.created_by = ? OR EXISTS (SELECT 1 FROM entity_shares s WHERE s.entity_type = 'competition' AND s.entity_id = t.id AND s.user_id = ?) ORDER BY t.start_date").all(user.id, user.id); else rows = db.prepare('SELECT * FROM tournaments WHERE is_private = 0 ORDER BY start_date').all(); return send(response, 200, rows.map(tournament), origin); }
    if (path === '/api/tournaments' && request.method === 'POST') { const user = actor(request); if (!user) return send(response, 401, { error: 'auth.required' }, origin); const input = await body(request); const id = randomUUID(); db.prepare('INSERT INTO tournaments (id, name, sport, location, start_date, status, logo_url, is_private, created_by) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)').run(id, input.name, input.sport, input.location, input.start_date, 'draft', input.logo_url ?? null, input.is_private ? 1 : 0, user.id); return send(response, 201, tournament(db.prepare('SELECT * FROM tournaments WHERE id = ?').get(id)), origin); }
    const tournamentMatch = path.match(/^\/api\/tournaments\/([^/]+)$/); if (tournamentMatch) { const current = db.prepare('SELECT * FROM tournaments WHERE id = ?').get(tournamentMatch[1]); const user = actor(request); if (!current) return send(response, 404, { error: 'tournaments.notFound' }, origin); if (current.is_private && !canAccessTournament(current.id, user)) return send(response, 403, { error: 'access.denied' }, origin); if (request.method === 'GET') return send(response, 200, tournament(current), origin); if (!manageable(current, user)) return send(response, 403, { error: 'tournaments.notAllowed' }, origin); if (request.method === 'DELETE') { db.prepare('DELETE FROM tournaments WHERE id = ?').run(current.id); return send(response, 200, { ok: true }, origin); } if (request.method === 'PATCH') { const input = await body(request); const logo = Object.hasOwn(input, 'logo_url') ? input.logo_url : current.logo_url; db.prepare('UPDATE tournaments SET name = coalesce(?, name), sport = coalesce(?, sport), location = coalesce(?, location), start_date = coalesce(?, start_date), status = coalesce(?, status), logo_url = ?, is_private = coalesce(?, is_private) WHERE id = ?').run(input.name ?? null, input.sport ?? null, input.location ?? null, input.start_date ?? null, input.status ?? null, logo, input.is_private === undefined ? null : (input.is_private ? 1 : 0), current.id); return send(response, 200, tournament(db.prepare('SELECT * FROM tournaments WHERE id = ?').get(current.id)), origin); } }
    const assignmentMatch = path.match(/^\/api\/tournaments\/([^/]+)\/teams(?:\/([^/]+))?$/); if (assignmentMatch) { const tournamentRow = db.prepare('SELECT * FROM tournaments WHERE id = ?').get(assignmentMatch[1]); const user = actor(request); if (!tournamentRow) return send(response, 404, { error: 'tournaments.notFound' }, origin); if (tournamentRow.is_private && !canAccessTournament(tournamentRow.id, user)) return send(response, 403, { error: 'access.denied' }, origin); if (request.method === 'GET') return send(response, 200, db.prepare('SELECT tm.* FROM teams tm JOIN tournament_teams tt ON tt.team_id = tm.id WHERE tt.tournament_id = ? ORDER BY tm.name').all(tournamentRow.id).map(team), origin); if (!manageable(tournamentRow, user)) return send(response, 403, { error: 'tournaments.notAllowed' }, origin); if (request.method === 'POST') { const input = await body(request); const id = randomUUID(); db.prepare('INSERT OR IGNORE INTO tournament_teams (id, tournament_id, team_id) VALUES (?, ?, ?)').run(id, tournamentRow.id, input.teamId); return send(response, 201, { ok: true }, origin); } if (request.method === 'DELETE' && assignmentMatch[2]) { db.prepare('DELETE FROM tournament_teams WHERE tournament_id = ? AND team_id = ?').run(tournamentRow.id, assignmentMatch[2]); return send(response, 200, { ok: true }, origin); } }
    const assignmentListRoute = path.match(/^\/api\/tournaments\/([^/]+)\/teams-assignments$/); if (assignmentListRoute && request.method === 'GET') { const tournamentRow = db.prepare('SELECT * FROM tournaments WHERE id = ?').get(assignmentListRoute[1]); const user = actor(request); if (!tournamentRow) return send(response, 404, { error: 'tournaments.notFound' }, origin); if (tournamentRow.is_private && !canAccessTournament(tournamentRow.id, user)) return send(response, 403, { error: 'access.denied' }, origin); return send(response, 200, db.prepare('SELECT * FROM tournament_teams WHERE tournament_id = ?').all(tournamentRow.id).map(tournamentTeam), origin); }
    if (path === '/api/sports' && request.method === 'GET') { const includeAll = url.searchParams.get('all') === '1'; if (includeAll && actor(request)?.role !== 'admin') return send(response, 403, { error: 'admin.accessDenied' }, origin); const rows = includeAll ? db.prepare('SELECT * FROM sports ORDER BY name').all() : db.prepare('SELECT * FROM sports WHERE active = 1 ORDER BY name').all(); return send(response, 200, rows.map(sport), origin); }
    if (path === '/api/sports' && request.method === 'POST') { const user = actor(request); if (user?.role !== 'admin') return send(response, 403, { error: 'admin.accessDenied' }, origin); const input = await body(request); const id = randomUUID(); db.prepare('INSERT INTO sports (id, name, code, active, scoring_type, periods_config) VALUES (?, ?, ?, ?, ?, ?)').run(id, input.name, input.code.toLowerCase(), input.active === false ? 0 : 1, input.scoring_type, input.periods_config || '{}'); return send(response, 201, sport(db.prepare('SELECT * FROM sports WHERE id = ?').get(id)), origin); }
    const sportRoute = path.match(/^\/api\/sports\/([^/]+)$/); if (sportRoute) { const user = actor(request); if (user?.role !== 'admin') return send(response, 403, { error: 'admin.accessDenied' }, origin); const current = db.prepare('SELECT * FROM sports WHERE id = ?').get(sportRoute[1]); if (!current) return send(response, 404, { error: 'sports.notFound' }, origin); if (request.method === 'PATCH') { const input = await body(request); db.prepare('UPDATE sports SET name = coalesce(?, name), code = coalesce(?, code), active = coalesce(?, active), scoring_type = coalesce(?, scoring_type), periods_config = coalesce(?, periods_config) WHERE id = ?').run(input.name ?? null, input.code?.toLowerCase() ?? null, input.active === undefined ? null : input.active ? 1 : 0, input.scoring_type ?? null, input.periods_config ?? null, current.id); return send(response, 200, sport(db.prepare('SELECT * FROM sports WHERE id = ?').get(current.id)), origin); } if (request.method === 'DELETE') { const used = db.prepare('SELECT (SELECT count(*) FROM tournaments WHERE sport = ?) + (SELECT count(*) FROM teams WHERE primary_sport = ?) AS value').get(current.code, current.code).value; if (used) return send(response, 409, { error: 'sports.inUse' }, origin); db.prepare('DELETE FROM sports WHERE id = ?').run(current.id); return send(response, 200, { ok: true }, origin); } }
    if (path === '/api/matches' && request.method === 'GET') { const user = actor(request); const tournamentId = url.searchParams.get('tournamentId'); let rows; if (user?.role === 'admin') rows = tournamentId ? db.prepare('SELECT * FROM matches WHERE tournament_id = ? ORDER BY match_date, match_time').all(tournamentId) : db.prepare('SELECT * FROM matches ORDER BY match_date, match_time').all(); else if (user) rows = tournamentId ? db.prepare("SELECT m.* FROM matches m JOIN tournaments t ON t.id = m.tournament_id WHERE m.tournament_id = ? AND (t.is_private = 0 OR t.created_by = ? OR EXISTS (SELECT 1 FROM entity_shares s WHERE s.entity_type = 'competition' AND s.entity_id = t.id AND s.user_id = ?)) ORDER BY m.match_date, m.match_time").all(tournamentId, user.id, user.id) : db.prepare("SELECT m.* FROM matches m JOIN tournaments t ON t.id = m.tournament_id WHERE t.is_private = 0 OR t.created_by = ? OR EXISTS (SELECT 1 FROM entity_shares s WHERE s.entity_type = 'competition' AND s.entity_id = t.id AND s.user_id = ?) ORDER BY m.match_date, m.match_time").all(user.id, user.id); else rows = tournamentId ? db.prepare('SELECT m.* FROM matches m JOIN tournaments t ON t.id = m.tournament_id WHERE m.tournament_id = ? AND t.is_private = 0 ORDER BY m.match_date, m.match_time').all(tournamentId) : db.prepare('SELECT m.* FROM matches m JOIN tournaments t ON t.id = m.tournament_id WHERE t.is_private = 0 ORDER BY m.match_date, m.match_time').all(); return send(response, 200, rows.map(match), origin); }
    if (path === '/api/matches' && request.method === 'POST') { const user = actor(request); if (!user) return send(response, 401, { error: 'auth.required' }, origin); const input = await body(request); const tournamentRow = db.prepare('SELECT * FROM tournaments WHERE id = ?').get(input.tournament_id); if (!manageable(tournamentRow, user)) return send(response, 403, { error: 'tournaments.notAllowed' }, origin); const registered = db.prepare('SELECT count(*) AS value FROM tournament_teams WHERE tournament_id = ? AND team_id IN (?, ?)').get(input.tournament_id, input.home_team_id, input.away_team_id).value; if (registered !== 2 || input.home_team_id === input.away_team_id) return send(response, 400, { error: 'matches.invalidTeams' }, origin); const id = randomUUID(); db.prepare('INSERT INTO matches (id, tournament_id, home_team_id, away_team_id, match_date, match_time, pitch_location, status, home_score, away_score) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)').run(id, input.tournament_id, input.home_team_id, input.away_team_id, input.match_date, input.match_time, input.pitch_location, 'scheduled', null, null); return send(response, 201, match(db.prepare('SELECT * FROM matches WHERE id = ?').get(id)), origin); }
    const matchRoute = path.match(/^\/api\/matches\/([^/]+)$/); if (matchRoute) { const current = db.prepare('SELECT * FROM matches WHERE id = ?').get(matchRoute[1]); if (!current) return send(response, 404, { error: 'matches.notFound' }, origin); const tournamentRow = db.prepare('SELECT * FROM tournaments WHERE id = ?').get(current.tournament_id); const user = actor(request); if (!manageable(tournamentRow, user)) return send(response, 403, { error: 'tournaments.notAllowed' }, origin); if (request.method === 'DELETE') { db.prepare('DELETE FROM matches WHERE id = ?').run(current.id); return send(response, 200, { ok: true }, origin); } if (request.method === 'PATCH') { const input = await body(request); db.prepare('UPDATE matches SET home_team_id = coalesce(?, home_team_id), away_team_id = coalesce(?, away_team_id), match_date = coalesce(?, match_date), match_time = coalesce(?, match_time), pitch_location = coalesce(?, pitch_location), status = coalesce(?, status), home_score = ?, away_score = ? WHERE id = ?').run(input.home_team_id ?? null, input.away_team_id ?? null, input.match_date ?? null, input.match_time ?? null, input.pitch_location ?? null, input.status ?? null, Object.hasOwn(input, 'home_score') ? input.home_score : current.home_score, Object.hasOwn(input, 'away_score') ? input.away_score : current.away_score, current.id); return send(response, 200, match(db.prepare('SELECT * FROM matches WHERE id = ?').get(current.id)), origin); } }
    const generateRoute = path.match(/^\/api\/tournaments\/([^/]+)\/generate-schedule$/); if (generateRoute && request.method === 'POST') { const tournamentRow = db.prepare('SELECT * FROM tournaments WHERE id = ?').get(generateRoute[1]); const user = actor(request); if (!manageable(tournamentRow, user)) return send(response, 403, { error: 'tournaments.notAllowed' }, origin); const input = await body(request); const teamRows = db.prepare('SELECT team_id FROM tournament_teams WHERE tournament_id = ? ORDER BY team_id').all(tournamentRow.id); if (teamRows.length < 2) return send(response, 400, { error: 'matches.notEnoughTeams' }, origin); let created = 0; const insert = db.prepare('INSERT INTO matches (id, tournament_id, home_team_id, away_team_id, match_date, match_time, pitch_location, status) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'); db.transaction(() => { for (let home = 0; home < teamRows.length; home++) for (let away = home + 1; away < teamRows.length; away++) { const exists = db.prepare('SELECT 1 FROM matches WHERE tournament_id = ? AND ((home_team_id = ? AND away_team_id = ?) OR (home_team_id = ? AND away_team_id = ?))').get(tournamentRow.id, teamRows[home].team_id, teamRows[away].team_id, teamRows[away].team_id, teamRows[home].team_id); if (!exists) { const minutes = created * 30; const hour = 9 + Math.floor(minutes / 60); const minute = minutes % 60; insert.run(randomUUID(), tournamentRow.id, teamRows[home].team_id, teamRows[away].team_id, input.match_date ?? tournamentRow.start_date, `${String(hour).padStart(2, '0')}:${String(minute).padStart(2, '0')}`, input.pitch_location ?? tournamentRow.location, 'scheduled'); created++; } } })(); return send(response, 201, { created }, origin); }
    const accessRoute = path.match(/^\/api\/matches\/([^/]+)\/access$/); if (accessRoute && request.method === 'POST') { const current = db.prepare('SELECT * FROM matches WHERE id = ?').get(accessRoute[1]); const tournamentRow = current && db.prepare('SELECT * FROM tournaments WHERE id = ?').get(current.tournament_id); const user = actor(request); if (!manageable(tournamentRow, user)) return send(response, 403, { error: 'tournaments.notAllowed' }, origin); let pin; do { pin = String(Math.floor(100000 + Math.random() * 900000)); } while (db.prepare('SELECT 1 FROM match_access_codes WHERE pin = ?').get(pin)); const token = randomUUID(); const expires = new Date(Date.now() + 12 * 3600000).toISOString(); db.prepare('DELETE FROM match_access_codes WHERE match_id = ?').run(current.id); db.prepare('INSERT INTO match_access_codes (id, match_id, pin, token, expires_at, created_by) VALUES (?, ?, ?, ?, ?, ?)').run(randomUUID(), current.id, pin, token, expires, user.id); return send(response, 201, { pin, token, expires_at: expires }, origin); }
    if (path === '/api/scorekeeper/access' && request.method === 'POST') { const input = await body(request); const access = db.prepare('SELECT * FROM match_access_codes WHERE (pin = ? OR token = ?) AND expires_at > ?').get(input.secret, input.secret, new Date().toISOString()); if (!access) return send(response, 401, { error: 'scorekeeper.invalid' }, origin); const current = db.prepare('SELECT * FROM matches WHERE id = ?').get(access.match_id); const home = db.prepare('SELECT * FROM teams WHERE id = ?').get(current.home_team_id); const away = db.prepare('SELECT * FROM teams WHERE id = ?').get(current.away_team_id); const events = db.prepare('SELECT * FROM match_events WHERE match_id = ? ORDER BY created_at, rowid').all(current.id).map(event); const homeRoster = db.prepare('SELECT r.* FROM tournament_rosters r JOIN tournament_teams tt ON tt.id = r.tournament_team_id WHERE tt.tournament_id = ? AND tt.team_id = ? ORDER BY r.is_captain DESC, r.last_name, r.first_name').all(current.tournament_id, current.home_team_id).map(rosterPlayer); const awayRoster = db.prepare('SELECT r.* FROM tournament_rosters r JOIN tournament_teams tt ON tt.id = r.tournament_team_id WHERE tt.tournament_id = ? AND tt.team_id = ? ORDER BY r.is_captain DESC, r.last_name, r.first_name').all(current.tournament_id, current.away_team_id).map(rosterPlayer); return send(response, 200, { match: match(current), homeTeam: team(home), awayTeam: team(away), events, homeRoster, awayRoster }, origin); }
    const publicMatchRoute = path.match(/^\/api\/public\/matches\/([^/]+)$/); if (publicMatchRoute && request.method === 'GET') { const current = db.prepare('SELECT * FROM matches WHERE id = ?').get(publicMatchRoute[1]); const user = actor(request); if (!current) return send(response, 404, { error: 'matches.notFound' }, origin); const tournamentRow = db.prepare('SELECT * FROM tournaments WHERE id = ?').get(current.tournament_id); if (tournamentRow.is_private && !canAccessTournament(tournamentRow.id, user)) return send(response, 403, { error: 'access.denied' }, origin); return send(response, 200, { match: match(current), homeTeam: team(db.prepare('SELECT * FROM teams WHERE id = ?').get(current.home_team_id)), awayTeam: team(db.prepare('SELECT * FROM teams WHERE id = ?').get(current.away_team_id)), events: db.prepare('SELECT * FROM match_events WHERE match_id = ? ORDER BY created_at, rowid').all(current.id).map(event) }, origin); }
    if (path === '/api/scorekeeper/event' && request.method === 'POST') { const input = await body(request); const access = db.prepare('SELECT * FROM match_access_codes WHERE (pin = ? OR token = ?) AND expires_at > ?').get(input.secret, input.secret, new Date().toISOString()); if (!access) return send(response, 401, { error: 'scorekeeper.invalid' }, origin); const current = db.prepare('SELECT * FROM matches WHERE id = ?').get(access.match_id); let clock = current.clock_seconds; if (current.clock_started_at) clock += Math.max(0, Math.floor((Date.now() - new Date(current.clock_started_at).getTime()) / 1000)); let deltaHome = 0; let deltaAway = 0; let playerName = input.player_name ?? null; if (input.roster_player_id) { const roster = db.prepare('SELECT r.first_name, r.last_name FROM tournament_rosters r JOIN tournament_teams tt ON tt.id = r.tournament_team_id WHERE r.id = ? AND tt.team_id = ? AND tt.tournament_id = ?').get(input.roster_player_id, input.team_id, current.tournament_id); playerName = roster ? `${roster.first_name} ${roster.last_name}`.trim() : playerName; } if (input.event_type === 'score') { if (input.team_id === current.home_team_id) deltaHome = 1; else if (input.team_id === current.away_team_id) deltaAway = 1; else return send(response, 400, { error: 'matches.invalidTeams' }, origin); db.prepare('UPDATE matches SET home_score = coalesce(home_score, 0) + ?, away_score = coalesce(away_score, 0) + ? WHERE id = ?').run(deltaHome, deltaAway, current.id); } if (input.event_type === 'timer_start') db.prepare("UPDATE matches SET status = 'live', clock_started_at = ? WHERE id = ?").run(new Date().toISOString(), current.id); if (input.event_type === 'timer_pause') db.prepare('UPDATE matches SET clock_seconds = ?, clock_started_at = NULL WHERE id = ?').run(clock, current.id); db.prepare('INSERT INTO match_events (id, match_id, event_type, team_id, roster_player_id, player_name, score_delta_home, score_delta_away, clock_seconds) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)').run(randomUUID(), current.id, input.event_type, input.team_id ?? null, input.roster_player_id ?? null, playerName, deltaHome, deltaAway, clock); return send(response, 201, { ok: true }, origin); }
    if (path === '/api/scorekeeper/undo' && request.method === 'POST') { const input = await body(request); const access = db.prepare('SELECT * FROM match_access_codes WHERE (pin = ? OR token = ?) AND expires_at > ?').get(input.secret, input.secret, new Date().toISOString()); if (!access) return send(response, 401, { error: 'scorekeeper.invalid' }, origin); const event = db.prepare("SELECT * FROM match_events WHERE match_id = ? AND event_type IN ('score', 'yellow_card', 'red_card') ORDER BY created_at DESC, rowid DESC LIMIT 1").get(access.match_id); if (!event) return send(response, 400, { error: 'scorekeeper.nothingToUndo' }, origin); db.transaction(() => { db.prepare('UPDATE matches SET home_score = max(0, coalesce(home_score, 0) - ?), away_score = max(0, coalesce(away_score, 0) - ?) WHERE id = ?').run(event.score_delta_home, event.score_delta_away, access.match_id); db.prepare('DELETE FROM match_events WHERE id = ?').run(event.id); })(); return send(response, 200, { ok: true }, origin); }
    const rosterLockRoute = path.match(/^\/api\/tournament-teams\/([^/]+)\/roster-lock$/); if (rosterLockRoute && request.method === 'PATCH') { const tt = db.prepare('SELECT * FROM tournament_teams WHERE id = ?').get(rosterLockRoute[1]); if (!tt) return send(response, 404, { error: 'tournaments.notFound' }, origin); const tournamentRow = db.prepare('SELECT * FROM tournaments WHERE id = ?').get(tt.tournament_id); const user = actor(request); if (!manageable(tournamentRow, user)) return send(response, 403, { error: 'tournaments.notAllowed' }, origin); const input = await body(request); db.prepare('UPDATE tournament_teams SET rosters_locked = ? WHERE id = ?').run(input.locked ? 1 : 0, tt.id); return send(response, 200, tournamentTeam(db.prepare('SELECT * FROM tournament_teams WHERE id = ?').get(tt.id)), origin); }
    const teamRostersRoute = path.match(/^\/api\/teams\/([^/]+)\/rosters$/); if (teamRostersRoute && request.method === 'GET') return send(response, 200, db.prepare('SELECT * FROM team_rosters WHERE team_id = ? ORDER BY last_name, first_name').all(teamRostersRoute[1]).map(rosterPlayer), origin); if (teamRostersRoute && request.method === 'POST') { const currentTeam = db.prepare('SELECT * FROM teams WHERE id = ?').get(teamRostersRoute[1]); const user = actor(request); if (!manageable(currentTeam, user)) return send(response, 403, { error: 'teams.notAllowed' }, origin); const input = await body(request); const id = randomUUID(); db.prepare('INSERT INTO team_rosters (id, team_id, created_by, user_id, first_name, last_name, jersey_number, position, is_captain) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)').run(id, currentTeam.id, user.id, input.user_id ?? null, input.first_name, input.last_name, input.jersey_number ?? null, input.position ?? null, input.is_captain ? 1 : 0); return send(response, 201, rosterPlayer(db.prepare('SELECT * FROM team_rosters WHERE id = ?').get(id)), origin); }
    const teamRosterRoute = path.match(/^\/api\/team-rosters\/([^/]+)$/); if (teamRosterRoute && request.method === 'GET') { const row = db.prepare('SELECT * FROM team_rosters WHERE id = ?').get(teamRosterRoute[1]); if (!row) return send(response, 404, { error: 'rosters.notFound' }, origin); return send(response, 200, rosterPlayer(row), origin); } if (teamRosterRoute && request.method === 'PATCH') { const row = db.prepare('SELECT * FROM team_rosters WHERE id = ?').get(teamRosterRoute[1]); if (!row) return send(response, 404, { error: 'rosters.notFound' }, origin); const currentTeam = db.prepare('SELECT * FROM teams WHERE id = ?').get(row.team_id); const user = actor(request); if (!manageable(currentTeam, user)) return send(response, 403, { error: 'teams.notAllowed' }, origin); const input = await body(request); db.prepare('UPDATE team_rosters SET first_name = coalesce(?, first_name), last_name = coalesce(?, last_name), jersey_number = ?, position = ?, is_captain = coalesce(?, is_captain) WHERE id = ?').run(input.first_name ?? null, input.last_name ?? null, input.jersey_number ?? null, input.position ?? null, input.is_captain === undefined ? null : input.is_captain ? 1 : 0, row.id); return send(response, 200, rosterPlayer(db.prepare('SELECT * FROM team_rosters WHERE id = ?').get(row.id)), origin); } const teamRosterLinkRoute = path.match(/^\/api\/team-rosters\/([^/]+)\/link$/); if (teamRosterLinkRoute && request.method === 'PATCH') { const row = db.prepare('SELECT * FROM team_rosters WHERE id = ?').get(teamRosterLinkRoute[1]); if (!row) return send(response, 404, { error: 'rosters.notFound' }, origin); const currentTeam = db.prepare('SELECT * FROM teams WHERE id = ?').get(row.team_id); const user = actor(request); if (!manageable(currentTeam, user)) return send(response, 403, { error: 'teams.notAllowed' }, origin); const input = await body(request); db.prepare('UPDATE team_rosters SET user_id = ? WHERE id = ?').run(input.userId ?? null, row.id); return send(response, 200, rosterPlayer(db.prepare('SELECT * FROM team_rosters WHERE id = ?').get(row.id)), origin); } if (teamRosterRoute && request.method === 'DELETE') { const row = db.prepare('SELECT * FROM team_rosters WHERE id = ?').get(teamRosterRoute[1]); if (!row) return send(response, 404, { error: 'rosters.notFound' }, origin); const currentTeam = db.prepare('SELECT * FROM teams WHERE id = ?').get(row.team_id); const user = actor(request); if (!manageable(currentTeam, user)) return send(response, 403, { error: 'teams.notAllowed' }, origin); db.prepare('DELETE FROM team_rosters WHERE id = ?').run(row.id); return send(response, 200, { ok: true }, origin); }
    const tournamentRostersRoute = path.match(/^\/api\/tournament-teams\/([^/]+)\/rosters$/); if (tournamentRostersRoute && request.method === 'GET') return send(response, 200, db.prepare('SELECT * FROM tournament_rosters WHERE tournament_team_id = ? ORDER BY is_captain DESC, last_name, first_name').all(tournamentRostersRoute[1]).map(rosterPlayer), origin); if (tournamentRostersRoute && request.method === 'POST') { const tt = db.prepare('SELECT * FROM tournament_teams WHERE id = ?').get(tournamentRostersRoute[1]); if (!tt) return send(response, 404, { error: 'tournaments.notFound' }, origin); const tournamentRow = db.prepare('SELECT * FROM tournaments WHERE id = ?').get(tt.tournament_id); const user = actor(request); if (!manageable(tournamentRow, user)) return send(response, 403, { error: 'tournaments.notAllowed' }, origin); if (tt.rosters_locked) return send(response, 403, { error: 'rosters.locked' }, origin); const input = await body(request); const id = randomUUID(); db.prepare('INSERT INTO tournament_rosters (id, tournament_team_id, user_id, first_name, last_name, jersey_number, position, is_captain) VALUES (?, ?, ?, ?, ?, ?, ?, ?)').run(id, tt.id, input.user_id ?? null, input.first_name, input.last_name, input.jersey_number ?? null, input.position ?? null, input.is_captain ? 1 : 0); return send(response, 201, rosterPlayer(db.prepare('SELECT * FROM tournament_rosters WHERE id = ?').get(id)), origin); }
    const tournamentRostersBulkRoute = path.match(/^\/api\/tournament-teams\/([^/]+)\/rosters\/bulk$/); if (tournamentRostersBulkRoute && request.method === 'POST') { const tt = db.prepare('SELECT * FROM tournament_teams WHERE id = ?').get(tournamentRostersBulkRoute[1]); if (!tt) return send(response, 404, { error: 'tournaments.notFound' }, origin); const tournamentRow = db.prepare('SELECT * FROM tournaments WHERE id = ?').get(tt.tournament_id); const user = actor(request); if (!manageable(tournamentRow, user)) return send(response, 403, { error: 'tournaments.notAllowed' }, origin); if (tt.rosters_locked) return send(response, 403, { error: 'rosters.locked' }, origin); const input = await body(request); let created = 0; const insert = db.prepare('INSERT INTO tournament_rosters (id, tournament_team_id, first_name, last_name, jersey_number, position, is_captain) VALUES (?, ?, ?, ?, ?, ?, ?)'); db.transaction(() => { for (const line of input.lines ?? []) { const trimmed = line.trim(); if (!trimmed) continue; const parsed = parseRosterLine(trimmed); if (parsed.first_name) { insert.run(randomUUID(), tt.id, parsed.first_name, parsed.last_name, parsed.jersey_number, null, 0); created++; } } })(); return send(response, 201, { created }, origin); }
    const tournamentRostersSyncRoute = path.match(/^\/api\/tournament-teams\/([^/]+)\/rosters\/sync$/); if (tournamentRostersSyncRoute && request.method === 'POST') { const tt = db.prepare('SELECT * FROM tournament_teams WHERE id = ?').get(tournamentRostersSyncRoute[1]); if (!tt) return send(response, 404, { error: 'tournaments.notFound' }, origin); const tournamentRow = db.prepare('SELECT * FROM tournaments WHERE id = ?').get(tt.tournament_id); const user = actor(request); if (!manageable(tournamentRow, user)) return send(response, 403, { error: 'tournaments.notAllowed' }, origin); if (tt.rosters_locked) return send(response, 403, { error: 'rosters.locked' }, origin); const existing = db.prepare('SELECT count(*) AS value FROM tournament_rosters WHERE tournament_team_id = ?').get(tt.id).value; if (existing) return send(response, 409, { error: 'rosters.exists' }, origin); const master = db.prepare('SELECT * FROM team_rosters WHERE team_id = ?').all(tt.team_id); const insert = db.prepare('INSERT INTO tournament_rosters (id, tournament_team_id, user_id, first_name, last_name, jersey_number, position, is_captain) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'); db.transaction(() => { for (const row of master) insert.run(randomUUID(), tt.id, row.user_id ?? null, row.first_name, row.last_name, row.jersey_number, row.position ?? null, row.is_captain ? 1 : 0); })(); return send(response, 201, { created: master.length }, origin); }
    const tournamentRosterLinkRoute = path.match(/^\/api\/tournament-teams\/([^/]+)\/rosters\/([^/]+)\/link$/); if (tournamentRosterLinkRoute && request.method === 'PATCH') { const tt = db.prepare('SELECT * FROM tournament_teams WHERE id = ?').get(tournamentRosterLinkRoute[1]); if (!tt) return send(response, 404, { error: 'tournaments.notFound' }, origin); const tournamentRow = db.prepare('SELECT * FROM tournaments WHERE id = ?').get(tt.tournament_id); const user = actor(request); if (!manageable(tournamentRow, user)) return send(response, 403, { error: 'tournaments.notAllowed' }, origin); const rosterId = tournamentRosterLinkRoute[2]; const input = await body(request); db.prepare('UPDATE tournament_rosters SET user_id = ? WHERE id = ? AND tournament_team_id = ?').run(input.userId ?? null, rosterId, tt.id); return send(response, 200, { ok: true }, origin); }
    const userStatsRoute = path.match(/^\/api\/users\/([^/]+)\/stats$/); if (userStatsRoute && request.method === 'GET') { const userId = userStatsRoute[1]; const matches = db.prepare('SELECT count(DISTINCT match_id) AS value FROM match_events WHERE roster_player_id IN (SELECT id FROM tournament_rosters WHERE user_id = ?)').get(userId).value; const goals = db.prepare("SELECT count(*) AS value FROM match_events WHERE event_type = 'score' AND roster_player_id IN (SELECT id FROM tournament_rosters WHERE user_id = ?)").get(userId).value; const yellows = db.prepare("SELECT count(*) AS value FROM match_events WHERE event_type = 'yellow_card' AND roster_player_id IN (SELECT id FROM tournament_rosters WHERE user_id = ?)").get(userId).value; const reds = db.prepare("SELECT count(*) AS value FROM match_events WHERE event_type = 'red_card' AND roster_player_id IN (SELECT id FROM tournament_rosters WHERE user_id = ?)").get(userId).value; return send(response, 200, { matchesPlayed: matches, goals, yellowCards: yellows, redCards: reds }, origin); }
    const userTeamsRoute = path.match(/^\/api\/users\/([^/]+)\/teams$/); if (userTeamsRoute && request.method === 'GET') { const userId = userTeamsRoute[1]; const rows = db.prepare("SELECT DISTINCT t.* FROM teams t JOIN team_rosters tr ON tr.team_id = t.id WHERE tr.user_id = ? UNION SELECT DISTINCT t.* FROM teams t JOIN tournament_teams tt ON tt.team_id = t.id JOIN tournament_rosters tor ON tor.tournament_team_id = tt.id WHERE tor.user_id = ? ORDER BY t.name").all(userId, userId); return send(response, 200, rows.map(team), origin); }
    const teamSharesRoute = path.match(/^\/api\/teams\/([^/]+)\/shares$/); if (teamSharesRoute) { const current = db.prepare('SELECT * FROM teams WHERE id = ?').get(teamSharesRoute[1]); const user = actor(request); if (!current) return send(response, 404, { error: 'teams.notFound' }, origin); if (!manageable(current, user)) return send(response, 403, { error: 'teams.notAllowed' }, origin); if (request.method === 'GET') { const rows = db.prepare("SELECT s.*, u.email, u.first_name, u.last_name FROM entity_shares s JOIN users u ON u.id = s.user_id WHERE s.entity_type = 'team' AND s.entity_id = ? ORDER BY u.last_name, u.first_name").all(current.id); return send(response, 200, rows.map((r) => ({ id: r.id, user_id: r.user_id, email: r.email, first_name: r.first_name, last_name: r.last_name, access_level: r.access_level })), origin); } if (request.method === 'POST') { const input = await body(request); db.prepare("INSERT OR IGNORE INTO entity_shares (id, entity_type, entity_id, user_id, access_level) VALUES (?, 'team', ?, ?, ?)").run(randomUUID(), current.id, input.userId, input.accessLevel ?? 'view'); return send(response, 201, { ok: true }, origin); } }
    const teamShareRoute = path.match(/^\/api\/teams\/([^/]+)\/shares\/([^/]+)$/); if (teamShareRoute && request.method === 'DELETE') { const current = db.prepare('SELECT * FROM teams WHERE id = ?').get(teamShareRoute[1]); const user = actor(request); if (!current) return send(response, 404, { error: 'teams.notFound' }, origin); if (!manageable(current, user)) return send(response, 403, { error: 'teams.notAllowed' }, origin); db.prepare("DELETE FROM entity_shares WHERE entity_type = 'team' AND entity_id = ? AND user_id = ?").run(current.id, teamShareRoute[2]); return send(response, 200, { ok: true }, origin); }
    const tournamentSharesRoute = path.match(/^\/api\/tournaments\/([^/]+)\/shares$/); if (tournamentSharesRoute) { const current = db.prepare('SELECT * FROM tournaments WHERE id = ?').get(tournamentSharesRoute[1]); const user = actor(request); if (!current) return send(response, 404, { error: 'tournaments.notFound' }, origin); if (!manageable(current, user)) return send(response, 403, { error: 'tournaments.notAllowed' }, origin); if (request.method === 'GET') { const rows = db.prepare("SELECT s.*, u.email, u.first_name, u.last_name FROM entity_shares s JOIN users u ON u.id = s.user_id WHERE s.entity_type = 'competition' AND s.entity_id = ? ORDER BY u.last_name, u.first_name").all(current.id); return send(response, 200, rows.map((r) => ({ id: r.id, user_id: r.user_id, email: r.email, first_name: r.first_name, last_name: r.last_name, access_level: r.access_level })), origin); } if (request.method === 'POST') { const input = await body(request); db.prepare("INSERT OR IGNORE INTO entity_shares (id, entity_type, entity_id, user_id, access_level) VALUES (?, 'competition', ?, ?, ?)").run(randomUUID(), current.id, input.userId, input.accessLevel ?? 'view'); return send(response, 201, { ok: true }, origin); } }
    const tournamentShareRoute = path.match(/^\/api\/tournaments\/([^/]+)\/shares\/([^/]+)$/); if (tournamentShareRoute && request.method === 'DELETE') { const current = db.prepare('SELECT * FROM tournaments WHERE id = ?').get(tournamentShareRoute[1]); const user = actor(request); if (!current) return send(response, 404, { error: 'tournaments.notFound' }, origin); if (!manageable(current, user)) return send(response, 403, { error: 'tournaments.notAllowed' }, origin); db.prepare("DELETE FROM entity_shares WHERE entity_type = 'competition' AND entity_id = ? AND user_id = ?").run(current.id, tournamentShareRoute[2]); return send(response, 200, { ok: true }, origin); }
    return send(response, 404, { error: 'notFound' }, origin);
  } catch (error) { const code = String(error.code ?? '').includes('UNIQUE') ? 409 : 400; return send(response, code, { error: error.message || 'request.failed' }, origin); }
});

server.listen(3210, '0.0.0.0', () => console.log(`SQLite API running at http://127.0.0.1:3210 (${databasePath})`));
process.on('SIGTERM', () => { db.close(); server.close(); });
