import { Redirect, router } from 'expo-router';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Image, Pressable, ScrollView, Text, TextInput, View } from 'react-native';

import { ConfirmDeleteModal } from '@/components/confirm-delete-modal';
import { EditProfileModal } from '@/components/edit-profile-modal';
import { RolePicker } from '@/components/role-picker';
import { TeamFormModal } from '@/components/team-form-modal';
import { TournamentFormModal } from '@/components/tournament-form-modal';
import { Button } from '@/components/ui/button';
import { createTeam, createTournament, deleteLocalUser, deleteMatch, deleteTeam, deleteTournament, getAdminMetrics, listLocalUsers, subscribeLocalData, subscribeLocalUsers, updateLocalUser, updateMatch, updateTeam, updateTournament } from '@/features/auth/local-db';
import { useMatches, useTeams, useTournaments } from '@/features/auth/use-local-data';
import { useAuth } from '@/providers/auth-provider';
import type { AdminMetrics, EditableProfile, Match, MatchStatus, Team, Tournament, UserProfile } from '@/types/database';
import { fullName, initialsFromName } from '@/types/database';

export type AdminTab = 'overview' | 'users' | 'tournaments' | 'teams' | 'matches' | 'sports';
type DeleteTarget = { kind: 'user' | 'tournament' | 'team' | 'match'; id: string; name: string };
const tabs: AdminTab[] = ['overview', 'users', 'tournaments', 'teams'];
const matchStatuses: MatchStatus[] = ['scheduled', 'live', 'finished', 'cancelled'];

function MatchOverride({ match, teamNames, admin, onDelete }: { match: Match; teamNames: Map<string, string>; admin: UserProfile; onDelete: () => void }) {
  const { t } = useTranslation(); const [home, setHome] = useState(match.home_score?.toString() ?? ''); const [away, setAway] = useState(match.away_score?.toString() ?? '');
  const save = () => updateMatch(match.id, { home_score: home === '' ? null : Number(home), away_score: away === '' ? null : Number(away) }, admin);
  return <View className="rounded-2xl border border-slate-200 bg-white p-5"><Text className="text-lg font-black text-ink">{teamNames.get(match.home_team_id)} — {teamNames.get(match.away_team_id)}</Text><Text className="mt-1 text-sm text-muted">{match.match_date} · {match.match_time} · {match.pitch_location}</Text><View className="mt-4 flex-row flex-wrap items-end gap-3"><View className="w-24"><Text className="mb-2 text-xs font-bold text-muted">{t('matches.homeScore')}</Text><TextInput value={home} onChangeText={setHome} keyboardType="number-pad" className="min-h-11 rounded-xl border border-slate-300 px-3 text-center font-black text-ink outline-none" /></View><View className="w-24"><Text className="mb-2 text-xs font-bold text-muted">{t('matches.awayScore')}</Text><TextInput value={away} onChangeText={setAway} keyboardType="number-pad" className="min-h-11 rounded-xl border border-slate-300 px-3 text-center font-black text-ink outline-none" /></View><Button label={t('common.save')} onPress={() => void save()} /><View className="flex-row flex-wrap gap-2">{matchStatuses.map((status) => <Pressable key={status} onPress={() => void updateMatch(match.id, { status }, admin)} className={`rounded-xl px-3 py-3 ${match.status === status ? 'bg-brand' : 'bg-slate-100'}`}><Text className={match.status === status ? 'font-bold text-white' : 'font-bold text-muted'}>{t(`matches.status.${status}`)}</Text></Pressable>)}</View><Pressable onPress={onDelete} className="rounded-xl bg-red-600 px-4 py-3"><Text className="font-black text-white">{t('delete.button')}</Text></Pressable></View></View>;
}

export function AdminDashboard({ initialTab = 'overview' }: { initialTab?: AdminTab }) {
  const { t } = useTranslation(); const { profile, loading } = useAuth(); const { data: teams } = useTeams(); const { data: tournaments } = useTournaments(); const { data: matches } = useMatches();
  const [tab] = useState<AdminTab>(initialTab); const [collapsed, setCollapsed] = useState(false); const [users, setUsers] = useState<UserProfile[]>([]); const [metrics, setMetrics] = useState<AdminMetrics | null>(null); const [editingUser, setEditingUser] = useState<UserProfile | null>(null); const [editingTeam, setEditingTeam] = useState<Team | null>(null); const [editingTournament, setEditingTournament] = useState<Tournament | null>(null); const [creatingTeam, setCreatingTeam] = useState(false); const [creatingTournament, setCreatingTournament] = useState(false); const [deleting, setDeleting] = useState<DeleteTarget | null>(null);
  const refresh = useCallback(() => { void listLocalUsers().then(setUsers); void getAdminMetrics().then(setMetrics); }, []);
  useEffect(() => { if (profile?.role !== 'admin') return; const timeout = setTimeout(refresh, 0); const unsubscribeUsers = subscribeLocalUsers(refresh); const unsubscribeData = subscribeLocalData(refresh); return () => { clearTimeout(timeout); unsubscribeUsers(); unsubscribeData(); }; }, [profile?.role, refresh]);
  const names = useMemo(() => new Map(teams.map((team) => [team.id, team.name])), [teams]);
  if (loading) return <View className="flex-1 bg-canvas" />; if (!profile) return <Redirect href="/sign-in" />; if (profile.role !== 'admin') return <View className="flex-1 items-center justify-center bg-canvas"><Text className="text-2xl font-black text-ink">{t('admin.accessDenied')}</Text></View>;
  const confirmDelete = async () => { if (!deleting) return; if (deleting.kind === 'user') await deleteLocalUser(deleting.id); if (deleting.kind === 'team') await deleteTeam(deleting.id, profile); if (deleting.kind === 'tournament') await deleteTournament(deleting.id, profile); if (deleting.kind === 'match') await deleteMatch(deleting.id, profile); setDeleting(null); refresh(); };
  const metricCards = [{ key: 'users', value: metrics?.users ?? 0 }, { key: 'activeTournaments', value: metrics?.activeTournaments ?? 0 }, { key: 'teams', value: metrics?.teams ?? 0 }, { key: 'databaseSize', value: `${Math.ceil((metrics?.databaseBytes ?? 0) / 1024)} KB` }];
  return <View className="flex-1 flex-row bg-canvas"><View className={`${collapsed ? 'w-20' : 'w-64'} hidden border-r border-slate-800 bg-ink p-4 md:flex`}><Pressable onPress={() => setCollapsed(!collapsed)} className="mb-6 rounded-xl bg-slate-800 p-3"><Text className="text-center font-black text-white">{collapsed ? '→' : '←'}</Text></Pressable>{tabs.map((item) => <Pressable key={item} onPress={() => router.push((item === 'overview' ? '/admin' : `/admin/${item}`) as never)} className={`mb-2 rounded-xl p-4 ${tab === item ? 'bg-brand' : ''}`}><Text className={`font-black ${tab === item ? 'text-white' : 'text-slate-300'}`}>{collapsed ? t(`admin.tabs.${item}`).slice(0, 1) : t(`admin.tabs.${item}`)}</Text></Pressable>)}<Pressable onPress={() => router.push('/admin/sports' as never)} className="mb-2 rounded-xl p-4"><Text className={`font-black ${tab === 'sports' ? 'text-white' : 'text-slate-300'}`}>{collapsed ? 'S' : t('admin.tabs.sports')}</Text></Pressable><Pressable onPress={() => router.push('/admin/matches' as never)} className="mb-2 rounded-xl p-4"><Text className={`font-black ${tab === 'matches' ? 'text-white' : 'text-slate-300'}`}>{collapsed ? 'M' : t('admin.tabs.matches')}</Text></Pressable></View><ScrollView className="flex-1" contentContainerClassName="items-center px-4 pb-24 pt-6 md:px-8"><View className="w-full max-w-6xl"><View className="mb-6 flex-row gap-2 overflow-hidden md:hidden">{tabs.map((item) => <Pressable key={item} onPress={() => router.push((item === 'overview' ? '/admin' : `/admin/${item}`) as never)} className={`rounded-xl px-3 py-3 ${tab === item ? 'bg-brand' : 'bg-white'}`}><Text className={`text-xs font-black ${tab === item ? 'text-white' : 'text-ink'}`}>{t(`admin.tabs.${item}`)}</Text></Pressable>)}<Pressable onPress={() => router.push('/admin/sports' as never)} className={`rounded-xl px-3 py-3 ${tab === 'sports' ? 'bg-brand' : 'bg-white'}`}><Text className={`text-xs font-black ${tab === 'sports' ? 'text-white' : 'text-ink'}`}>{t('admin.tabs.sports')}</Text></Pressable><Pressable onPress={() => router.push('/admin/matches' as never)} className={`rounded-xl px-3 py-3 ${tab === 'matches' ? 'bg-brand' : 'bg-white'}`}><Text className={`text-xs font-black ${tab === 'matches' ? 'text-white' : 'text-ink'}`}>{t('admin.tabs.matches')}</Text></Pressable></View><Text className="text-xs font-black uppercase tracking-widest text-brand">{t('admin.badge')}</Text><Text className="mt-2 text-4xl font-black text-ink">{t(`admin.tabs.${tab}`)}</Text><Text className="mt-2 text-muted">{t('admin.subtitle')}</Text>
    {tab === 'overview' ? <View className="mt-7 flex-row flex-wrap gap-4">{metricCards.map((item) => <View key={item.key} className="min-w-48 flex-1 rounded-2xl bg-ink p-6"><Text className="text-4xl font-black text-emerald-400">{item.value}</Text><Text className="mt-2 font-bold text-slate-300">{t(`admin.metrics.${item.key}`)}</Text></View>)}</View> : null}
    {tab === 'users' ? <View className="mt-7 gap-3">{users.map((user) => <View key={user.id} className="flex-row flex-wrap items-center gap-4 rounded-2xl bg-white p-5"><View className="min-w-52 flex-1"><Text className="font-black text-ink">{fullName(user)}</Text><Text className="mt-1 text-sm text-muted">{user.email} · {user.id}</Text></View><RolePicker user={user} /><Button label={t('common.edit')} variant="ghost" onPress={() => setEditingUser(user)} /><Pressable onPress={() => setDeleting({ kind: 'user', id: user.id, name: fullName(user) })} className="rounded-xl bg-red-600 px-4 py-3"><Text className="font-black text-white">{t('delete.button')}</Text></Pressable></View>)}</View> : null}
    {tab === 'teams' ? <View className="mt-7"><View className="mb-4 items-start"><Button label={t('teams.create')} onPress={() => setCreatingTeam(true)} /></View><View className="flex-row flex-wrap gap-3">{teams.map((team) => <View key={team.id} className="min-w-64 flex-1 rounded-2xl bg-white p-5"><View style={{ backgroundColor: team.color }} className="h-12 w-12 items-center justify-center overflow-hidden rounded-xl">{team.logo_url ? <Image source={{ uri: team.logo_url }} className="h-full w-full" resizeMode="cover" /> : <Text className="font-black text-white">{initialsFromName(team.name)}</Text>}</View><Text className="mt-4 text-xl font-black text-ink">{team.name}</Text><View className="mt-4 flex-row gap-2"><Button label={t('common.edit')} variant="ghost" onPress={() => setEditingTeam(team)} /><Pressable onPress={() => setDeleting({ kind: 'team', id: team.id, name: team.name })} className="rounded-xl bg-red-600 px-4 py-3"><Text className="font-black text-white">{t('delete.button')}</Text></Pressable></View></View>)}</View></View> : null}
    {tab === 'tournaments' ? <View className="mt-7"><View className="mb-4 items-start"><Button label={t('tournaments.create')} onPress={() => setCreatingTournament(true)} /></View><View className="gap-3">{tournaments.map((tournament) => <View key={tournament.id} className="flex-row flex-wrap items-center gap-4 rounded-2xl bg-white p-5"><View className="min-w-52 flex-1"><Text className="text-xl font-black text-ink">{tournament.name}</Text><Text className="mt-1 text-muted">{tournament.location} · {t(`tournaments.status.${tournament.status}`)}</Text></View><View className="flex-row gap-2"><Button label={t('common.edit')} variant="ghost" onPress={() => setEditingTournament(tournament)} /><Pressable onPress={() => setDeleting({ kind: 'tournament', id: tournament.id, name: tournament.name })} className="rounded-xl bg-red-600 px-4 py-3"><Text className="font-black text-white">{t('delete.button')}</Text></Pressable></View></View>)}</View></View> : null}
    {tab === 'matches' ? <View className="mt-7 gap-3">{matches.map((item) => <MatchOverride key={item.id} match={item} teamNames={names} admin={profile} onDelete={() => setDeleting({ kind: 'match', id: item.id, name: `${names.get(item.home_team_id)} — ${names.get(item.away_team_id)}` })} />)}</View> : null}
  </View></ScrollView>{editingUser ? <EditProfileModal profile={editingUser} onClose={() => setEditingUser(null)} onSave={async (values: EditableProfile) => { await updateLocalUser(editingUser.id, values); }} /> : null}{editingTeam ? <TeamFormModal team={editingTeam} onClose={() => setEditingTeam(null)} onSave={async (values) => updateTeam(editingTeam.id, values, profile)} /> : null}{creatingTeam ? <TeamFormModal onClose={() => setCreatingTeam(false)} onSave={async (values) => { await createTeam(values, profile); }} /> : null}{editingTournament ? <TournamentFormModal tournament={editingTournament} showStatus onClose={() => setEditingTournament(null)} onSave={async (values) => { await updateTournament(editingTournament.id, values, profile); }} /> : null}{creatingTournament ? <TournamentFormModal onClose={() => setCreatingTournament(false)} onSave={async (values) => { await createTournament(values, profile); }} /> : null}{deleting ? <ConfirmDeleteModal name={deleting.name} onCancel={() => setDeleting(null)} onConfirm={confirmDelete} /> : null}</View>;
}

export default function AdminScreen() {
  return <AdminDashboard />;
}
