import { router } from 'expo-router';
import { useState } from 'react';
import { useTranslation } from 'react-i18next';
import { ActivityIndicator, Image, Pressable, ScrollView, Text, View } from 'react-native';

import { EditProfileModal } from '@/components/edit-profile-modal';
import { Button } from '@/components/ui/button';
import { useAuth } from '@/providers/auth-provider';

export default function ProfileScreen() {
  const { t } = useTranslation();
  const { profile, loading, signOut, updateProfile } = useAuth();
  const [editing, setEditing] = useState(false);
  if (loading) return <View className="flex-1 items-center justify-center bg-canvas"><ActivityIndicator color="#10B981" /></View>;
  if (!profile) return <View className="flex-1 items-center justify-center bg-canvas px-5"><View className="w-full max-w-md rounded-2xl bg-white p-7 shadow-sm"><Text className="text-3xl font-black text-ink">{t('profile.title')}</Text><Text className="mt-2 text-muted">{t('auth.required')}</Text><View className="mt-6 gap-3"><Button label={t('nav.signIn')} onPress={() => router.push('/sign-in')} /><Button label={t('nav.signUp')} variant="ghost" onPress={() => router.push('/sign-up')} /></View></View></View>;
  const initials = profile.displayName.split(' ').map((part) => part[0]).join('').slice(0, 2).toUpperCase();
  return <ScrollView className="flex-1 bg-canvas" contentContainerClassName="items-center px-5 pb-24 pt-10"><View className="w-full max-w-4xl gap-6"><View className="flex-row flex-wrap items-end justify-between gap-4"><View><Text className="text-sm font-black uppercase tracking-widest text-brand">{t('common.appName')}</Text><Text className="mt-2 text-4xl font-black text-ink">{t('profile.title')}</Text><Text className="mt-2 text-muted">{t('profile.subtitle')}</Text></View></View><View className="overflow-hidden rounded-2xl bg-ink p-7 md:p-10"><View className="flex-row flex-wrap items-center gap-6"><View style={{ backgroundColor: profile.profileColor }} className="h-28 w-28 items-center justify-center overflow-hidden rounded-2xl">{profile.avatarUrl ? <Image source={{ uri: profile.avatarUrl }} className="h-full w-full" resizeMode="cover" /> : <Text className="text-4xl font-black text-white">{initials}</Text>}</View><View className="min-w-60 flex-1"><Text className="text-3xl font-black text-white">{profile.displayName}</Text><Text className="mt-2 text-slate-300">{profile.email}</Text><View className="mt-4 self-start rounded-full bg-emerald-500/15 px-4 py-2"><Text className="font-black text-emerald-400">{t(`profile.${profile.role}`)}</Text></View></View></View></View><View className="flex-row flex-wrap gap-4"><View className="min-w-52 flex-1 rounded-2xl bg-white p-6"><Text className="text-xs font-black uppercase tracking-widest text-muted">{t('profile.favoriteSport')}</Text><Text className="mt-3 text-xl font-black text-ink">{t(`sports.${profile.favoriteSport}`)}</Text></View><View className="min-w-52 flex-1 rounded-2xl bg-white p-6"><Text className="text-xs font-black uppercase tracking-widest text-muted">{t('profile.memberSince')}</Text><Text className="mt-3 text-xl font-black text-ink">{new Date(profile.createdAt).toLocaleDateString()}</Text></View></View><View className="sticky bottom-4 flex-row flex-wrap gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-xl"><Button label={t('profile.edit')} onPress={() => setEditing(true)} /><Button label={t('profile.signOut')} variant="ghost" onPress={() => void signOut()} />{profile.role === 'admin' ? <Pressable onPress={() => router.push('/admin')} className="min-h-12 items-center justify-center rounded-xl bg-ink px-5"><Text className="font-black text-white">{t('nav.admin')}</Text></Pressable> : null}</View></View>{editing ? <EditProfileModal profile={profile} onClose={() => setEditing(false)} onSave={updateProfile} /> : null}</ScrollView>;
}
