import { useLocalSearchParams } from 'expo-router';
import { useCallback, useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Pressable, ScrollView, Text, TextInput, View } from 'react-native';

import { getScorekeeperMatch, recordMatchEvent, undoMatchEvent } from '@/features/auth/local-db';
import type { PublicMatch } from '@/types/database';

function clock(seconds: number) { return `${Math.floor(seconds / 60).toString().padStart(2, '0')}:${(seconds % 60).toString().padStart(2, '0')}`; }
export default function ScorekeeperScreen() {
  const { t } = useTranslation(); const params = useLocalSearchParams<{ secret?: string }>(); const [secret, setSecret] = useState(params.secret ?? ''); const [activeSecret, setActiveSecret] = useState(params.secret ?? ''); const [bundle, setBundle] = useState<PublicMatch | null>(null); const [error, setError] = useState(''); const [now, setNow] = useState(0); const [player, setPlayer] = useState('');
  const refresh = useCallback(async () => { if (!activeSecret) return; try { setBundle(await getScorekeeperMatch(activeSecret)); setError(''); } catch (reason) { setError(t(reason instanceof Error ? reason.message : 'scorekeeper.invalid')); } }, [activeSecret, t]);
  useEffect(() => { const timeout = setTimeout(refresh, 0); const interval = setInterval(() => { setNow(Date.now()); void refresh(); }, 1000); return () => { clearTimeout(timeout); clearInterval(interval); }; }, [refresh]);
  const action = async (event_type: 'score' | 'yellow_card' | 'red_card' | 'timer_start' | 'timer_pause', team_id: string | null = null) => { await recordMatchEvent(activeSecret, { event_type, team_id, player_name: player || null }); await refresh(); };
  if (!bundle) return <View className="flex-1 items-center justify-center bg-ink px-5"><View className="w-full max-w-md rounded-2xl bg-white p-6"><Text className="text-3xl font-black text-ink">{t('scorekeeper.title')}</Text><Text className="mt-2 text-muted">{t('scorekeeper.enter')}</Text><TextInput value={secret} onChangeText={setSecret} keyboardType="number-pad" className="mt-6 min-h-14 rounded-xl border border-slate-300 px-4 text-center text-2xl font-black text-ink outline-none" placeholder="123456" /><Pressable onPress={() => setActiveSecret(secret.trim())} className="mt-4 min-h-14 items-center justify-center rounded-xl bg-brand"><Text className="font-black text-white">{t('scorekeeper.open')}</Text></Pressable>{error ? <Text className="mt-3 font-bold text-red-600">{error}</Text> : null}</View></View>;
  const running = bundle.match.clock_started_at ? Math.max(0, Math.floor((now - new Date(bundle.match.clock_started_at).getTime()) / 1000)) : 0; const elapsed = bundle.match.clock_seconds + running;
  return <ScrollView className="flex-1 bg-ink" contentContainerClassName="items-center px-4 pb-12 pt-6"><View className="w-full max-w-xl gap-4"><Text className="text-center text-xs font-black uppercase tracking-widest text-emerald-400">{t('scorekeeper.sideline')}</Text><Text className="text-center font-mono text-5xl font-black text-white">{clock(elapsed)}</Text><View className="flex-row rounded-2xl bg-white p-6"><View className="flex-1 items-center"><Text className="text-center font-black text-ink">{bundle.homeTeam.name}</Text><Text className="mt-3 text-6xl font-black text-ink">{bundle.match.home_score ?? 0}</Text></View><View className="flex-1 items-center"><Text className="text-center font-black text-ink">{bundle.awayTeam.name}</Text><Text className="mt-3 text-6xl font-black text-ink">{bundle.match.away_score ?? 0}</Text></View></View><TextInput value={player} onChangeText={setPlayer} className="min-h-12 rounded-xl bg-white px-4 text-ink outline-none" placeholder={t('scorekeeper.player')} /><View className="flex-row gap-3">{[bundle.homeTeam, bundle.awayTeam].map((team) => <View key={team.id} className="flex-1 gap-3"><Text className="text-center font-black text-white">{team.short_name}</Text><Pressable onPress={() => void action('score', team.id)} className="min-h-24 items-center justify-center rounded-2xl bg-brand"><Text className="text-2xl font-black text-white">+1 {t('scorekeeper.point')}</Text></Pressable><Pressable onPress={() => void action('yellow_card', team.id)} className="min-h-16 items-center justify-center rounded-2xl bg-yellow-400"><Text className="font-black text-ink">{t('scorekeeper.yellow')}</Text></Pressable><Pressable onPress={() => void action('red_card', team.id)} className="min-h-16 items-center justify-center rounded-2xl bg-red-600"><Text className="font-black text-white">{t('scorekeeper.red')}</Text></Pressable></View>)}</View><View className="flex-row gap-3"><Pressable onPress={() => void action(bundle.match.clock_started_at ? 'timer_pause' : 'timer_start')} className="min-h-16 flex-1 items-center justify-center rounded-2xl bg-white"><Text className="font-black text-ink">{t(bundle.match.clock_started_at ? 'scorekeeper.pause' : 'scorekeeper.start')}</Text></Pressable><Pressable onPress={() => void undoMatchEvent(activeSecret).then(refresh)} className="min-h-16 flex-1 items-center justify-center rounded-2xl border border-red-500"><Text className="font-black text-red-400">{t('scorekeeper.undo')}</Text></Pressable></View></View></ScrollView>;
}
