import { useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Modal, ScrollView, Text, View } from 'react-native';

import { DatePickerField } from '@/components/date-picker-field';
import { Button } from '@/components/ui/button';
import { Field } from '@/components/ui/field';
import type { Match, MatchStatus, Team } from '@/types/database';
import { initialsFromName } from '@/types/database';

const statuses: MatchStatus[] = ['scheduled', 'live', 'finished', 'cancelled'];
export function MatchEditModal({ match, teams, onClose, onSave }: { match: Match; teams: Team[]; onClose: () => void; onSave: (values: Partial<Match>) => Promise<void> }) {
  const { t } = useTranslation(); const [home, setHome] = useState(match.home_team_id); const [away, setAway] = useState(match.away_team_id); const [date, setDate] = useState(match.match_date); const [time, setTime] = useState(match.match_time); const [pitch, setPitch] = useState(match.pitch_location); const [homeScore, setHomeScore] = useState(match.home_score?.toString() ?? ''); const [awayScore, setAwayScore] = useState(match.away_score?.toString() ?? ''); const [status, setStatus] = useState(match.status); const [saving, setSaving] = useState(false);
  const selector = (value: string, setValue: (id: string) => void, label: string) => <View className="gap-2"><Text className="text-sm font-bold text-ink">{label}</Text><View className="flex-row flex-wrap gap-2">{teams.map((team) => <Button key={team.id} label={initialsFromName(team.name)} size="sm" variant={value === team.id ? 'primary' : 'ghost'} onPress={() => setValue(team.id)} />)}</View></View>;
  const save = async () => { setSaving(true); try { await onSave({ home_team_id: home, away_team_id: away, match_date: date, match_time: time, pitch_location: pitch, home_score: homeScore === '' ? null : Number(homeScore), away_score: awayScore === '' ? null : Number(awayScore), status }); onClose(); } finally { setSaving(false); } };
  return <Modal visible transparent animationType="fade"><View className="flex-1 items-center justify-center bg-slate-950/80 px-4"><ScrollView className="max-h-[90%] w-full max-w-xl rounded-2xl bg-white" contentContainerClassName="gap-4 p-6"><Text className="text-2xl font-black text-ink">{t('matchesAdmin.edit')}</Text>{selector(home, setHome, t('matches.home'))}{selector(away, setAway, t('matches.away'))}<DatePickerField label={t('matches.matchDate')} value={date} onChange={setDate} /><Field label={t('matches.time')} value={time} onChangeText={setTime} /><Field label={t('matches.pitch')} value={pitch} onChangeText={setPitch} /><View className="flex-row gap-3"><View className="flex-1"><Field label={t('matches.homeScore')} value={homeScore} onChangeText={setHomeScore} keyboardType="number-pad" /></View><View className="flex-1"><Field label={t('matches.awayScore')} value={awayScore} onChangeText={setAwayScore} keyboardType="number-pad" /></View></View><View className="flex-row flex-wrap gap-2">{statuses.map((item) => <Button key={item} label={t(`matches.status.${item}`)} size="sm" variant={status === item ? 'primary' : 'ghost'} onPress={() => setStatus(item)} />)}</View><View className="flex-row gap-3"><View className="flex-1"><Button label={t('common.cancel')} variant="ghost" onPress={onClose} /></View><View className="flex-1"><Button label={t('common.save')} onPress={() => void save()} loading={saving} disabled={home === away} /></View></View></ScrollView></View></Modal>;
}
